# Generated by Django 3.0.5 on 2020-04-22 17:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Journey',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(choices=[('VAL', 'Vallikavu'), ('KYJ', 'Kayamkulam'), ('KPI', 'Karunagapalli')], max_length=3)),
                ('destination', models.CharField(choices=[('VAL', 'Vallikavu'), ('KYJ', 'Kayamkulam'), ('KPI', 'Karunagapalli')], max_length=3)),
                ('datefield', models.DateField()),
                ('timefield', models.TimeField()),
                ('preference', models.IntegerField()),
                ('status', models.CharField(choices=[('DONE', 'DONE'), ('UPCO', 'Upcoming')], max_length=4)),
                ('profilename', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(blank=True, max_length=100)),
                ('last_name', models.CharField(blank=True, max_length=100)),
                ('email', models.CharField(max_length=150)),
                ('category', models.CharField(choices=[('STUD', 'Student'), ('DRIV', 'Driver')], default='STUD', max_length=4)),
                ('phone', models.CharField(max_length=10)),
                ('signup_confirmation', models.BooleanField(default=False)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Teams',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='login.Journey')),
                ('pid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='login.Profile')),
            ],
        ),
    ]
