# Generated by Django 3.0.5 on 2020-04-22 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='teams',
            name='arri',
            field=models.CharField(default='None', max_length=10),
        ),
    ]
