# Generated by Django 3.0.4 on 2020-03-08 15:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0002_profile_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='Journey',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('source', models.CharField(choices=[('VAL', 'Vallikavu'), ('KYJ', 'Kayamkulam'), ('KPI', 'Karunagapalli')], max_length=3)),
                ('destination', models.CharField(choices=[('VAL', 'Vallikavu'), ('KYJ', 'Kayamkulam'), ('KPI', 'Karunagapalli')], max_length=3)),
                ('datefield', models.DateField()),
                ('timefield', models.TimeField()),
                ('preference', models.IntegerField()),
                ('status', models.CharField(choices=[('PAST', 'Past'), ('UPCO', 'Upcoming')], max_length=4)),
                ('profile', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='login.Profile')),
            ],
        ),
    ]
