# Generated by Django 3.0.5 on 2020-04-25 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0002_teams_arri'),
    ]

    operations = [
        migrations.AlterField(
            model_name='journey',
            name='status',
            field=models.CharField(max_length=100),
        ),
    ]
