# Generated by Django 3.0.5 on 2020-04-28 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0003_auto_20200425_1916'),
    ]

    operations = [
        migrations.AddField(
            model_name='teams',
            name='teamid',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
