# Generated by Django 3.0.4 on 2020-03-08 15:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0006_auto_20200308_1531'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Journey',
        ),
    ]
