# Generated by Django 3.0.4 on 2020-03-08 15:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0009_auto_20200308_1535'),
    ]

    operations = [
        migrations.RenameField(
            model_name='journey',
            old_name='username',
            new_name='profilename',
        ),
    ]
