# Generated by Django 3.0.4 on 2020-03-08 15:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0010_auto_20200308_1544'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Journey',
        ),
    ]
